**Lab Assignment 2 - Robert Fyfe (200007440)**

Repository URL: https://github.com/fyfey26/PY4SA23_Assignment.git

In [2]:
number=10
if number/3:
    print("10 is divisible by 3")
else:
    print("10 is not divisible by 3")

10 is divisible by 3

In [3]:
List=["apple","orange","pear","kiwi","strawberry"]
if "pear" in List:
    print("pear is acceptable")
else:
    print("pear is not acceptable")

pear is acceptable

In [5]:
from math import radians, cos, sin, asin, sqrt, atan2, degrees

def haversine (A,B):
    lat1=A[0]
    lon1=A[1]
    
    lat2=B[0]
    lon2=B[1]
    
    lat1,lon1,lat2,lon2=map(radians,[lat1,lon1,lat2,lon2])
    
    dlon=lon2-lon1
    dlat=lat2-lat1
    a=sin(dlat/2)**2+cos(lat1)*cos(lat2)*sin(dlon/2)**2
    c=2*atan2(sqrt(a),(sqrt(1-a)))
    R=6371
    return(R*c)
ans=haversine([2,1],[1,2])
print (ans)

157.22543203807288

In [8]:
import numpy as np
import pandas as pd

trees_df=pd.read_csv('portland_park_trees.csv')
trees_df.query('(Genus=="Acer" | Genus=="Quercus")')

,fid,OBJECTID,Inventory_,Species,DBH,Condition,TreeHeight,CrownWidth,CrownWid_1,CollectedB,...,Genus,Common_nam,Genus_spec,Functional,Size,Native,Edible,Nuisance,Origin,Species_fa
3,4,429,2017/05/09,QURU,10.3,Poor,28.0,38.0,31.0,staff,...,Quercus,northern red oak,Quercus rubra,BD,L,No,NaN,NaN,North America - eastern Canada and eastern USA...,Acorns take two years to mature and are an imp...
11,12,437,2017/05/09,QURU,14.9,Fair,48.0,33.0,27.0,staff,...,Quercus,northern red oak,Quercus rubra,BD,L,No,NaN,NaN,North America - eastern Canada and eastern USA...,Acorns take two years to mature and are an imp...
24,25,450,2017/05/15,ACGR,6.6,Fair,19.0,17.0,13.0,staff,...,Acer,paperbark maple,Acer griseum,BD,S,No,NaN,NaN,Asia - central China,Easily identified by its red-brown bark that p...
25,26,451,2017/05/15,ACGR,6.2,Fair,27.0,14.0,14.0,staff,...,Acer,paperbark maple,Acer griseum,BD,S,No,NaN,NaN,Asia - central China,Easily identified by its red-brown bark that p...
30,31,456,2017/05/15,ACPL,17.3,Fair,44.0,50.0,40.0,staff,...,Acer,Norway maple,Acer platanoides,BD,M,No,NaN,Yes,Europe - from Scandinavia and western Europe (...,Most common street tree in Portland. Pull a le...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25506,25507,724045,2019/10/11,ACMA,63.0,Poor,46.0,56.0,55.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
25508,25509,724047,2019/10/11,ACMA,35.0,Fair,57.0,52.0,42.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
25511,25512,724444,2019/10/11,ACMA,38.4,Fair,102.0,42.0,41.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
25516,25517,724843,2019/10/11,ACMA,19.0,Fair,64.0,45.0,41.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
25529,25530,726046,2018/08/16,QURU,31.6,Fair,74.0,50.0,46.0,volunteer,...,Quercus,northern red oak,Quercus rubra,BD,L,No,NaN,NaN,North America - eastern Canada and eastern USA...,Acorns take two years to mature and are an imp...

In [11]:
trees_df.query('(Genus=="Acer" | Genus=="Quercus") & DBH>50')

,fid,OBJECTID,Inventory_,Species,DBH,Condition,TreeHeight,CrownWidth,CrownWid_1,CollectedB,...,Genus,Common_nam,Genus_spec,Functional,Size,Native,Edible,Nuisance,Origin,Species_fa
127,128,953,2017/05/24,ACMA,50.5,Fair,90.0,83.0,84.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
152,153,1754,2017/05/24,ACMA,50.5,Fair,85.0,51.0,60.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
154,155,1756,2017/05/24,ACMA,52.7,Fair,94.0,73.0,59.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
162,163,2150,2017/05/24,ACMA,56.3,Fair,70.0,57.0,72.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
593,594,13044,2017/06/29,ACMA,50.9,Fair,90.0,59.0,64.0,volunteer,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23957,23958,684418,2019/09/23,ACMA,59.5,Poor,77.0,40.0,32.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
24271,24272,690856,2019/09/25,QUGA,69.9,Good,101.0,83.0,117.0,staff,...,Quercus,Oregon white oak,Quercus garryana,BD,L,Yes,Yes - nuts,NaN,"North America - southern British Columbia, Can...","Look for galls on the underside of leaves, whi..."
24461,24462,695648,2019/09/27,QUGA,59.0,Fair,94.0,97.0,89.0,staff,...,Quercus,Oregon white oak,Quercus garryana,BD,L,Yes,Yes - nuts,NaN,"North America - southern British Columbia, Can...","Look for galls on the underside of leaves, whi..."
25499,25500,723643,2019/10/11,ACMA,84.5,Fair,69.0,62.0,67.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."
25506,25507,724045,2019/10/11,ACMA,63.0,Poor,46.0,56.0,55.0,staff,...,Acer,bigleaf maple,Acer macrophyllum,BD,L,Yes,NaN,NaN,North America - Oregon and Washington west of ...,"Name comes from the large five-lobed leaves, m..."

In [15]:
trees_df.loc[trees_df['Genus']=='Acer','DBH'].mean()

18.419085331846066

In [13]:
trees_df.loc[trees_df['Genus']=='Quercus','DBH'].mean()

23.56823839157492

In [16]:
trees_df.loc[trees_df['Genus']=='Fraxinus','DBH'].mean()

11.033609693877551

In [17]:
trees_df.loc[trees_df['Genus']=='Acer','Species'].nunique()

20

In [20]:
cities_df=pd.read_csv('world_cities.csv')
cities_df['pop_M'] = cities_df['pop']/1000000
cities_df.head()

                 city    country    pop    lat    lon  capital     pop_M
0  'Abasan al-Jadidah  Palestine   5629  31.31  34.34        0  0.005629
1  'Abasan al-Kabirah  Palestine  18999  31.32  34.35        0  0.018999
2        'Abdul Hakim   Pakistan  47788  30.55  72.11        0  0.047788
3  'Abdullah-as-Salam     Kuwait  21817  29.36  47.98        0  0.021817
4               'Abud  Palestine   2456  32.03  35.07        0  0.002456

In [21]:
cities_df.drop('pop',axis=1)

                     city       country    lat    lon  capital     pop_M
0      'Abasan al-Jadidah     Palestine  31.31  34.34        0  0.005629
1      'Abasan al-Kabirah     Palestine  31.32  34.35        0  0.018999
2            'Abdul Hakim      Pakistan  30.55  72.11        0  0.047788
3      'Abdullah-as-Salam        Kuwait  29.36  47.98        0  0.021817
4                   'Abud     Palestine  32.03  35.07        0  0.002456
...                   ...           ...    ...    ...      ...       ...
43640           az-Zubayr          Iraq  30.39  47.71        0  0.124611
43641            az-Zulfi  Saudi Arabia  26.30  44.80        0  0.054070
43642       az-Zuwaytinah         Libya  30.95  20.12        0  0.021984
43643        s-Gravenhage   Netherlands  52.07   4.30        0  0.479525
43644     s-Hertogenbosch   Netherlands  51.68   5.30        0  0.135529

[43645 rows x 6 columns]

In [24]:
cities_df.loc[cities_df['country']=='Brazil'].nlargest(5,'pop','all')

                 city country       pop    lat    lon  capital      pop_M
33834       Sao Paulo  Brazil  10059502 -23.53 -46.63        0  10.059502
31332  Rio de Janeiro  Brazil   6055582 -22.91 -43.20        0   6.055582
32565        Salvador  Brazil   2762758 -12.97 -38.50        0   2.762758
3943   Belo Horizonte  Brazil   2399577 -19.92 -43.94        0   2.399577
11697       Fortaleza  Brazil   2349632  -3.78 -38.59        0   2.349632